(
~words = [
    [2, 1, 1, 2, 2, 1, 2],
    [1, 2, 1, 1, 2, 1, 2, 1],
    [1, 2, 1, 2, 1, 2, 1, 2],
    [2, 1, 1, 2, 1, 1, 2, 1, 1],
    [2, 1, 2, 2, 1, 2, 2, 1, 2],
    [1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
    [2, 1, 1, 2, 1, 2, 1, 1, 2, 1]
];
~wordIndex = 0;
~word = ~words[0];
~morph = 0.0;
// Niveaux d'envoi par voix (0 à 1)
~sendReverb1 = 0.3;
~sendDelay1  = 0.0;
~sendReverb2 = 0.3;
~sendDelay2  = 0.0;
)


